name: DOCS
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Auto build documentation
      run: |
        npm ci jsdoc2md
        npm run build:docs
      
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "DOCS: Automated docs update" -a | exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
