name: CI
on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 13]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: node --version
    - run: npm ci
    - name: Run unittests
      run: npm run test
    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        name: actions ${{ matrix.node }}
        fail_ci_if_error: false
